services:
  backend-dev:
    image: ghcr.io/satuundangan/satuundangan-backend:latest
    container_name: satu-undangan-api-dev
    restart: always
    ports:
      - "3001:3000"
    env_file: .env.dev
    # Pakai network yang sama supaya bisa akses mysql-db
    networks:
      - satu-undangan_default
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  satu-undangan_default:
    external: true
