export const DEFAULT_CHECKLISTS = [
  // 1. Fase H-180 s/d H-120 (6 - 4 Bulan Sebelum Hari H) - Fondasi & Legalitas
  {
    id: 'chk-1',
    phase: 'H-180 s/d H-120',
    category: 'Administrasi & Konsep',
    task: 'Pertemuan silaturahmi dua keluarga besar & penentuan tanggal pernikahan resmi',
    isCompleted: false,
    priority: 'high',
    notes: 'Sepakati tanggal akad & resepsi, serta format acara (gabung atau terpisah)',
  },
  {
    id: 'chk-2',
    phase: 'H-180 s/d H-120',
    category: 'Budgeting & Finansial',
    task: 'Menentukan estimasi total anggaran (budget) & pembagian porsi kedua keluarga',
    isCompleted: false,
    priority: 'high',
    notes: 'Gunakan kalkulator budget SatuUndangan untuk menetapkan pagu biaya per pos',
  },
  {
    id: 'chk-3',
    phase: 'H-180 s/d H-120',
    category: 'Administrasi & Konsep',
    task: 'Menentukan tema & konsep pernikahan (Adat Tradisional, Nasional, Modern, atau Intimate)',
    isCompleted: false,
    priority: 'medium',
    notes: 'Tentukan warna tema (palette) & dress code keluarga',
  },
  {
    id: 'chk-4',
    phase: 'H-180 s/d H-120',
    category: 'Venue & Gedung',
    task: 'Survey & booking Venue / Gedung Akad & Resepsi (kunci tanggal dan bayar DP)',
    isCompleted: false,
    priority: 'high',
    notes: 'Pastikan kapasitas ruangan sesuai jumlah undangan dan ketersediaan parkir',
  },
  {
    id: 'chk-5',
    phase: 'H-180 s/d H-120',
    category: 'Katering',
    task: 'Survey & booking Katering utama (test food menu pilihan keluarga)',
    isCompleted: false,
    priority: 'high',
    notes: 'Hitung rumus porsi: 2x jumlah undangan (60% buffet, 40% stall gubukan)',
  },
  {
    id: 'chk-6',
    phase: 'H-180 s/d H-120',
    category: 'Wedding Organizer',
    task: 'Menentukan apakah butuh Wedding Organizer (WO) atau Tim Panitia Keluarga',
    isCompleted: false,
    priority: 'medium',
    notes: 'Bila pakai panitia keluarga, tunjuk Ketua Panitia & Koordinator Inti',
  },

  // 2. Fase H-90 s/d H-60 (3 - 2 Bulan Sebelum Hari H) - Vendor Inti & Dokumen KUA
  {
    id: 'chk-7',
    phase: 'H-90 s/d H-60',
    category: 'Legalitas & Dokumen',
    task: 'Urus berkas N1, N2, N4 dari Kelurahan & daftarkan pernikahan ke KUA / Catatan Sipil',
    isCompleted: false,
    priority: 'high',
    notes: 'Sertakan surat sehat Puskesmas/Catin dan bukti vaksin TT bagi calon pengantin wanita',
  },
  {
    id: 'chk-8',
    phase: 'H-90 s/d H-60',
    category: 'MUA & Busana',
    task: 'Booking MUA (Make Up Artist), Busana Pengantin & Fitting Baju Perdana',
    isCompleted: false,
    priority: 'high',
    notes: 'Pilih kebaya/beskap atau jas, serta seragam pendamping & orang tua',
  },
  {
    id: 'chk-9',
    phase: 'H-90 s/d H-60',
    category: 'Dokumentasi',
    task: 'Booking Fotografer & Videografer + jadwalkan sesi Prewedding',
    isCompleted: false,
    priority: 'medium',
    notes: 'Tentukan konsep photoshoot studio atau outdoor, siapkan moodboard foto',
  },
  {
    id: 'chk-10',
    phase: 'H-90 s/d H-60',
    category: 'Dekorasi & Tata Suara',
    task: 'Booking Vendor Dekorasi Pelaminan, Photo Booth, Lighting, & Sound System',
    isCompleted: false,
    priority: 'medium',
    notes: 'Sesuaikan denah panggung akad, mini gallery, serta jalur kirab pengantin',
  },
  {
    id: 'chk-11',
    phase: 'H-90 s/d H-60',
    category: 'Mahar & Cincin',
    task: 'Beli / Pesan Cincin Kawin (Grafir Nama) & Kotak Mahar Seserahan',
    isCompleted: false,
    priority: 'medium',
    notes: 'Siapkan nominal uang tunai / logam mulia mahar dan hiasan seserahan',
  },
  {
    id: 'chk-12',
    phase: 'H-90 s/d H-60',
    category: 'Undangan Digital',
    task: 'Buat Undangan Digital di SatuUndangan.id & susun database nama tamu',
    isCompleted: false,
    priority: 'high',
    notes: 'Pilih template eksklusif, input lokasi maps, rekening kado, dan impor daftar tamu',
  },

  // 3. Fase H-30 s/d H-7 (1 Bulan - 1 Minggu Sebelum Hari H) - Distribusi & Finalisasi
  {
    id: 'chk-13',
    phase: 'H-30 s/d H-7',
    category: 'Undangan Digital',
    task: 'Sebar Undangan Digital via WhatsApp menggunakan fitur SatuUndangan',
    isCompleted: false,
    priority: 'high',
    notes: 'Gunakan template pesan santun & personal ke teman kantor, sahabat, dan keluarga',
  },
  {
    id: 'chk-14',
    phase: 'H-30 s/d H-7',
    category: 'MUA & Busana',
    task: 'Final fitting busana pengantin, orang tua, dan seragam pagar ayu',
    isCompleted: false,
    priority: 'high',
    notes: 'Coba berjalan dengan sepatu/selop hak tinggi yang akan dipakai hari H',
  },
  {
    id: 'chk-15',
    phase: 'H-30 s/d H-7',
    category: 'Koordinasi Acara',
    task: 'Technical Meeting (TM) seluruh vendor dan keluarga inti di venue acara',
    isCompleted: false,
    priority: 'high',
    notes: 'Sinkronisasi rundown jam per jam, kebutuhan listrik, sound, serta akses katering',
  },
  {
    id: 'chk-16',
    phase: 'H-30 s/d H-7',
    category: 'Katering & Logistik',
    task: 'Cek rekap RSVP tamu SatuUndangan & kunci final order porsi katering',
    isCompleted: false,
    priority: 'high',
    notes: 'Hindari kehabisan makanan dengan memverifikasi konfirmasi kehadiran tamu di dashboard',
  },
  {
    id: 'chk-17',
    phase: 'H-30 s/d H-7',
    category: 'Suvenir & Resepsi',
    task: 'Ambil suvenir pernikahan & cetak Standee QR Code Meja Resepsi SatuUndangan',
    isCompleted: false,
    priority: 'medium',
    notes: 'Standee QR ditaruh di meja resepsi untuk check-in instan dan amplop digital cashless',
  },

  // 4. Fase Minggu Terakhir & Hari H (D-Day) - Relaksasi & Eksekusi Sempurna
  {
    id: 'chk-18',
    phase: 'Minggu Terakhir & Hari H',
    category: 'Kesehatan & Relaksasi',
    task: 'Perawatan diri calon pengantin (lulur, spa, istirahat cukup, hindari begadang)',
    isCompleted: false,
    priority: 'high',
    notes: 'Minum air putih cukup dan jaga pola makan agar wajah glowing dan fit saat akad',
  },
  {
    id: 'chk-19',
    phase: 'Minggu Terakhir & Hari H',
    category: 'Logistik Hari H',
    task: 'Siapkan Tas Darurat (Emergency Kit: jarum pentul, peniti, plester luka, obat maag/pusing, touch-up)',
    isCompleted: false,
    priority: 'high',
    notes: 'Titipkan tas ini kepada bridesmaid / adik kandung yang selalu mendampingi',
  },
  {
    id: 'chk-20',
    phase: 'Minggu Terakhir & Hari H',
    category: 'Buku Tamu & Resepsi',
    task: 'Briefing penerima tamu / pagar ayu untuk Scanner QR Buku Tamu SatuUndangan',
    isCompleted: false,
    priority: 'high',
    notes: 'Pastikan panitia membuka menu scanner di smartphone mereka untuk menyambut tamu',
  },
  {
    id: 'chk-21',
    phase: 'Minggu Terakhir & Hari H',
    category: 'Finansial & Dokumen',
    task: 'Siapkan amplop pelunasan sisa vendor dan dokumen resmi nikah (KTP & Mahar)',
    isCompleted: false,
    priority: 'high',
    notes: 'Simpan di tempat aman dan tunjuk 1 orang keluarga terpercaya sebagai penanggung jawab kas',
  },
];

export const DEFAULT_BUDGET_ITEMS = [
  {
    id: 'bgt-1',
    category: 'Venue & Gedung',
    name: 'Sewa Gedung / Ballroom Resepsi',
    estimatedCost: 15000000,
    actualCost: 15000000,
    paidAmount: 5000000,
    notes: 'Termasuk listrik, AC, kursi, & kebersihan',
  },
  {
    id: 'bgt-2',
    category: 'Katering',
    name: 'Paket Buffet & Gubukan (500 Porsi)',
    estimatedCost: 25000000,
    actualCost: 24000000,
    paidAmount: 10000000,
    notes: '5 menu buffet utama + 3 stall gubukan populer',
  },
  {
    id: 'bgt-3',
    category: 'Dekorasi',
    name: 'Dekorasi Pelaminan, Lorong & Photobooth',
    estimatedCost: 10000000,
    actualCost: 9500000,
    paidAmount: 3000000,
    notes: 'Bunga segar, karpet jalan, welcome sign aesthetic',
  },
  {
    id: 'bgt-4',
    category: 'MUA & Busana',
    name: 'MUA Pengantin, Ibu & Besan + Busana',
    estimatedCost: 7500000,
    actualCost: 7500000,
    paidAmount: 2500000,
    notes: 'Termasuk retouch, paes/siger, henna & softlens',
  },
  {
    id: 'bgt-5',
    category: 'Dokumentasi',
    name: 'Foto & Video Cinematic (Akad + Resepsi)',
    estimatedCost: 6000000,
    actualCost: 6000000,
    paidAmount: 2000000,
    notes: '2 fotografer, 1 videografer, teaser 1 menit & all raw files',
  },
  {
    id: 'bgt-6',
    category: 'Undangan & Digital',
    name: 'Undangan Digital SatuUndangan.id (Paket Exclusive)',
    estimatedCost: 99000,
    actualCost: 99000,
    paidAmount: 99000,
    notes: 'Aktif 1 tahun + QR Check-in Meja Resepsi',
  },
  {
    id: 'bgt-7',
    category: 'Suvenir & Mahar',
    name: 'Suvenir Tamu (300 pcs) + Kotak Mahar & Cincin',
    estimatedCost: 3500000,
    actualCost: 3200000,
    paidAmount: 1500000,
    notes: 'Suvenir pouch custom & jasa hias mahar',
  },
  {
    id: 'bgt-8',
    category: 'Wedding Organizer & Hiburan',
    name: 'Akustik / Sound System & MC Acara',
    estimatedCost: 3000000,
    actualCost: 2800000,
    paidAmount: 1000000,
    notes: 'MC akad dan resepsi 3 jam',
  },
];

export const DEFAULT_RUNDOWN = [
  {
    id: 'rdn-1',
    time: '05:30 - 07:30',
    activity: 'Make Up & Persiapan Pengantin + Orang Tua',
    location: 'Ruang Rias Pengantin',
    pic: 'MUA & Bridesmaid',
    notes: 'Sarapan ringan sebelum rias, siapkan baju akad',
  },
  {
    id: 'rdn-2',
    time: '07:30 - 08:00',
    activity: 'Kedatangan Calon Pengantin Pria & Keluarga',
    location: 'Lobi Depan Gedung',
    pic: 'Penerima Tamu Keluarga',
    notes: 'Penyambutan, kalung bunga melati & penyerahan seserahan',
  },
  {
    id: 'rdn-3',
    time: '08:00 - 09:30',
    activity: 'Prosesi Akad Nikah / Pemberkatan Resmi',
    location: 'Area Meja Akad / Altar',
    pic: 'Penghulu KUA / Pemuka Agama & MC',
    notes: 'Ijab kabul, penyerahan mahar, penandatanganan buku nikah & sesi foto',
  },
  {
    id: 'rdn-4',
    time: '09:30 - 10:30',
    activity: 'Retouch Busana Resepsi & Foto Keluarga Inti',
    location: 'Ruang Rias / Pelaminan',
    pic: 'MUA & Tim Dokumentasi',
    notes: 'Briefing tim resepsi, standee QR, dan koordinator katering',
  },
  {
    id: 'rdn-5',
    time: '11:00 - 13:00',
    activity: 'Resepsi Pernikahan (Kirab Pengantin, Ramah Tamah, Hiburan)',
    location: 'Main Ballroom',
    pic: 'WO / MC & Panitia Resepsi',
    notes: 'Check-in tamu via QR Scanner SatuUndangan di meja penerima tamu',
  },
  {
    id: 'rdn-6',
    time: '13:00 - 13:30',
    activity: 'Foto Bersama Sahabat, Vendor & Penutupan Acara',
    location: 'Pelaminan',
    pic: 'MC & WO',
    notes: 'Rekap amplop, standee QR, & serah terima barang keluarga',
  },
];
